index:
  path: /index
  controller: App\Controller\IndexController::Default
Products:
  path: /All/Products
  controller: App\Controller\IndexController::Products
catt:
  path: /All/Categories
  controller: App\Controller\IndexController::Array
array:
  path: /index/categories
  controller: App\Controller\IndexController::Array
ProdSearch:
  path: /index/product/{idProduct}
  controller: App\Controller\IndexController::FindProduct
useradd:
  path: /userAdd
  controller: App\Controller\IndexController::addUser
userConnect:
  path: /user
  controller: App\Controller\IndexController::checkUser
CategSearch:
  path: /index/categorie/{idCategorie}
  controller: App\Controller\IndexController::ProductsByCategorieId
